{% set name = "sirepo-bluesky" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a46084c1cf4ea031079cc51a663fb6368f57330a65bf89458e5276210fb68f9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - area-detector-handlers
    - bluesky >=1.11.0
    - databroker
    - inflection
    - ipython
    - matplotlib-base
    - numconv
    - numpy
    - ophyd
    - peakutils
    - pymongo
    - pyqt >=5.9
    - requests
    - shadow3 >=23.1.4
    - srwpy >=4.0.0b1
    - tfs-pandas
    - unyt
    - xraylib

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check || echo "No problem"
  imports:
    - sirepo_bluesky
    - sirepo_bluesky.madx_flyer
    - sirepo_bluesky.madx_handler
    - sirepo_bluesky.shadow_handler
    - sirepo_bluesky.sirepo_bluesky
    - sirepo_bluesky.sirepo_flyer
    - sirepo_bluesky.sirepo_ophyd
    - sirepo_bluesky.srw_handler

about:
  home: https://github.com/NSLS-II/sirepo-bluesky
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sirepo-Bluesky interface

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
